### ISSUE TITLE
[Feature]: New video

### ISSUE THREAD

**Issue by nickvidal** [enarx/try.enarx.dev#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Replace current video with a new one focused on showcasing Benefice.

### Suggestions for a technical implementation

This is the basic script for the "Try Enarx" video:

Hello and welcome to the Enarx project! Thank you for your interest in learning more!

The Enarx project allows you to deploy applications to a Keep (a type of Trusted Execution Environment), so that your code and data is protected while in use. Nobody has access to them, not even the Cloud Service Provider or anyone who has compromised it. This is called Confidential Computing.

We use WebAssembly as a way to abstract the complexities to achieve Confidential Computing. You can use whatever language you are most comfortable with and compile that to any platform, from Intel's SGX/TDX to AMD's SEV-SNP.

"Try Enarx" let's you try Enarx very easily. You can upload a Webassembly application straight from your browser and deploy it securily to an Enarx Keep. Let's demonstrate this:

Enter https://try.enarx.dev/

And select a platform.

First, we need to login using a GitHub account.

Next we'll upload a simple "Hello World" WebAssembly application:

https://enarx.dev/hello-world.wasm

And now we can see the output of this application running in an Enarx Keep.

I hope you enjoyed this demonstration.

You can run this same application in other platforms, such as Intel or AMD on Equinix, with many more coming soon.

We also have several guides that will help you get started, including a WebAssembly Guide.

Additionally, feel free to explore some demos that we have in the WebAssembly Gallery.

And finally, we welcome you to join our community at:

https://enarx.dev/

Thank you!

**Comment by haraldh** [comment]
> You can use whatever language you are most comfortable with and compile that to any platform, from Intel's SGX/TDX to AMD's SEV-SNP.

You can use whatever language you are most comfortable with and compile that to WebAssembly. Enarx can run this WebAssembly on any secure platform, from Intel's SGX to AMD's SEV-SNP and other future technologies.

**Comment by JenWike** [comment]
I am making tweaks to the script in this doc, please make suggestions with "suggestions" turned on, thanks!

https://docs.google.com/document/d/1fJNuKuMEp5cn84o-MfC4VJvy9FbOfB5ItDSjY0pJ5EU/edit#

**Comment by nickvidal** [comment]
Thanks @JenWike, video is complete and has been added to the landing page.
