### ISSUE TITLE
[Bug]: snp.equinix.try.enarx.dev - Failed to start workload: Bad Request

### ISSUE THREAD

**Issue by haraldh** [enarx/try.enarx.dev#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

Failed to start workload: Bad Request

### Expected Behaviour

no error

### Environment Information

https://snp.equinix.try.enarx.dev/

### Steps To Reproduce

1. select any workload
2. deploy
3. error

**Comment by dpal** [comment]
I just tried it. Works for me now. @haraldh can you please recheck?
