### ISSUE TITLE
[Documentation]: <Readme>

### ISSUE THREAD

**Issue by maveraw** [enarx/try.enarx.dev#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It would be nice to have a quick overview or a guide for the try enarx as soon as they see this repo. That's why from a beginner's perspective, I elaborated on the readme. I have created a patch. Kindly check on it. 

### Acceptance Criteria

https://github.com/maveraw/try.enarx.dev/pull/1

**Comment by dpal** [comment]
If you have a proposed patch, please create a PR. Please tag @nickvidal in the PR.

**Comment by maveraw** [comment]
hEY @dpal thanks for the response.  For sure.

**Comment by nickvidal** [comment]
Thanks @maveraw! Now you have to create a PR against the Try Enarx repo on Enarx.
